import type { Language } from './types';

export const UI_TEXT: Record<Language, Record<string, string>> = {
  ar: {
    title: "MarketMind",
    mainTitle: "MarketMind — ذكاء السوق بين يديك",
    subtitle: "تحليل لحظي للأسواق باستخدام الذكاء الاصطناعي.",
    searchPlaceholder: "أدخل اسم الأصل (مثل: بيتكوين, سهم أبل)...",
    uploadButton: "أو ارفع صورة شارت",
    analyzeButton: "تحليل الآن",
    analyzing: "جاري التحليل...",
    error: "حدث خطأ أثناء التحليل. يرجى المحاولة مرة أخرى.",
    errorApiExhausted: "تم تجاوز حصة API. يرجى الانتظار لحظة قبل محاولة التحديث مرة أخرى. تحقق من خطتك والفواتير لمزيد من التفاصيل.",
    errorJson: "استجاب النموذج بتنسيق غير متوقع. يرجى المحاولة مرة أخرى.",
    executiveSummary: "الملخص التنفيذي",
    latestNews: "آخر الأخبار",
    sentimentAnalysis: "تحليل المشاعر",
    technicalAnalysis: "التحليل الفني",
    priceActionReasons: "أبرز الأسباب المحتملة لتحرك السعر",
    confidenceScore: "درجة الثقة",
    positive: "إيجابي",
    negative: "سلبي",
    neutral: "محايد",
    trendingKeywords: "أهم الكلمات الرائجة",
    source: "المصدر",
    disclaimer: "هذا الموقع يقدم تحليلات معلوماتية باستخدام الذكاء الاصطناعي وليست نصيحة استثمارية. قم بأبحاثك الخاصة قبل اتخاذ أي قرارات مالية.",
    footerText: "© 2025 MarketMind — Developed by Mohammad Alsebaei",
    printReport: "طباعة التقرير",
    refreshButton: "تحديث",
    languageSwitch: "English",
    marketData: "بيانات السوق",
    currentPrice: "السعر الحالي",
    priceChange24h: "تغير (24 ساعة)",
    high24h: "أعلى (24 ساعة)",
    low24h: "أدنى (24 ساعة)",
    marketCap: "القيمة السوقية",
    volume24h: "حجم التداول (24 ساعة)",
    dataFreshness: "حالة البيانات",
  },
  en: {
    title: "MarketMind",
    mainTitle: "MarketMind — Market Intelligence in Your Hands",
    subtitle: "Real-time market analysis using artificial intelligence.",
    searchPlaceholder: "Enter asset name (e.g., Bitcoin, AAPL)...",
    uploadButton: "Or upload a chart image",
    analyzeButton: "Analyze Now",
    analyzing: "Analyzing...",
    error: "An error occurred during analysis. Please try again.",
    errorApiExhausted: "API quota exceeded. Please wait a moment before trying to refresh again. Check your plan and billing for more details.",
    errorJson: "The model responded with an unexpected format. Please try again.",
    executiveSummary: "Executive Summary",
    latestNews: "Latest News",
    sentimentAnalysis: "Sentiment Analysis",
    technicalAnalysis: "Technical Analysis",
    priceActionReasons: "Potential Reasons for Price Movement",
    confidenceScore: "Confidence Score",
    positive: "Positive",
    negative: "Negative",
    neutral: "Neutral",
    trendingKeywords: "Trending Keywords",
    source: "Source",
    disclaimer: "This site provides informational analysis using AI and is not investment advice. Always do your own research before making financial decisions.",
    footerText: "© 2025 MarketMind — Developed by Mohammad Alsebaei",
    printReport: "Print Report",
    refreshButton: "Refresh",
    languageSwitch: "العربية",
    marketData: "Market Data",
    currentPrice: "Current Price",
    priceChange24h: "24h Change",
    high24h: "24h High",
    low24h: "24h Low",
    marketCap: "Market Cap",
    volume24h: "Volume (24h)",
    dataFreshness: "Data Status",
  },
};